In [1]:
%reload_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
from fastai.structured import *
from fastai.column_data import *
np.set_printoptions(threshold=50, edgeitems=20)

PATH='data/porto_seguro_safe_driver_prediction/'

In [3]:
df = pd.read_csv(f'{PATH}train/train.csv', low_memory=False)

In [4]:
test = pd.read_csv(f'{PATH}test/test.csv', low_memory=False)

In [5]:
df.head()

,id,target,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,7,0,2,2,5,1,0,0,1,0,...,9,1,5,8,0,1,1,0,0,1
1,9,0,1,1,7,0,0,0,0,1,...,3,1,1,9,0,1,1,0,1,0
2,13,0,5,4,9,1,0,0,0,1,...,4,2,7,7,0,1,1,0,1,0
3,16,0,0,1,2,0,0,1,0,0,...,2,2,4,9,0,0,0,0,0,0
4,17,0,0,2,0,1,0,1,0,0,...,3,1,1,3,0,0,0,1,1,0

In [6]:
test.head()

,id,ps_ind_01,ps_ind_02_cat,ps_ind_03,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,...,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,ps_calc_15_bin,ps_calc_16_bin,ps_calc_17_bin,ps_calc_18_bin,ps_calc_19_bin,ps_calc_20_bin
0,0,0,1,8,1,0,0,1,0,0,...,1,1,1,12,0,1,1,0,0,1
1,1,4,2,5,1,0,0,0,0,1,...,2,0,3,10,0,0,1,1,0,1
2,2,5,1,3,0,0,0,0,0,1,...,4,0,2,4,0,0,0,0,0,0
3,3,0,1,6,0,0,1,0,0,0,...,5,1,0,5,1,0,1,0,0,0
4,4,5,1,7,0,0,0,0,0,1,...,4,0,0,4,0,1,1,0,0,1

In [5]:
df.columns

Index(['id', 'target', 'ps_ind_01', 'ps_ind_02_cat', 'ps_ind_03',
       'ps_ind_04_cat', 'ps_ind_05_cat', 'ps_ind_06_bin', 'ps_ind_07_bin',
       'ps_ind_08_bin', 'ps_ind_09_bin', 'ps_ind_10_bin', 'ps_ind_11_bin',
       'ps_ind_12_bin', 'ps_ind_13_bin', 'ps_ind_14', 'ps_ind_15',
       'ps_ind_16_bin', 'ps_ind_17_bin', 'ps_ind_18_bin', 'ps_reg_01',
       'ps_reg_02', 'ps_reg_03', 'ps_car_01_cat', 'ps_car_02_cat',
       'ps_car_03_cat', 'ps_car_04_cat', 'ps_car_05_cat', 'ps_car_06_cat',
       'ps_car_07_cat', 'ps_car_08_cat', 'ps_car_09_cat', 'ps_car_10_cat',
       'ps_car_11_cat', 'ps_car_11', 'ps_car_12', 'ps_car_13', 'ps_car_14',
       'ps_car_15', 'ps_calc_01', 'ps_calc_02', 'ps_calc_03', 'ps_calc_04',
       'ps_calc_05', 'ps_calc_06', 'ps_calc_07', 'ps_calc_08', 'ps_calc_09',
       'ps_calc_10', 'ps_calc_11', 'ps_calc_12', 'ps_calc_13', 'ps_calc_14',
       'ps_calc_15_bin', 'ps_calc_16_bin', 'ps_calc_17_bin', 'ps_calc_18_bin',
       'ps_calc_19_bin', 'ps_calc_20_bin'],
      dtype='object')

In [6]:
columns = df.columns

In [7]:
categorical = [col for col in columns if '_bin' in col or '_cat' in col]
continuous = [col for col in columns if '_bin' not in col and '_cat' not in col and col not in ['id', 'target']]

In [8]:
continuous, categorical

(['ps_ind_01',
  'ps_ind_03',
  'ps_ind_14',
  'ps_ind_15',
  'ps_reg_01',
  'ps_reg_02',
  'ps_reg_03',
  'ps_car_11',
  'ps_car_12',
  'ps_car_13',
  'ps_car_14',
  'ps_car_15',
  'ps_calc_01',
  'ps_calc_02',
  'ps_calc_03',
  'ps_calc_04',
  'ps_calc_05',
  'ps_calc_06',
  'ps_calc_07',
  'ps_calc_08',
  'ps_calc_09',
  'ps_calc_10',
  'ps_calc_11',
  'ps_calc_12',
  'ps_calc_13',
  'ps_calc_14'],
 ['ps_ind_02_cat',
  'ps_ind_04_cat',
  'ps_ind_05_cat',
  'ps_ind_06_bin',
  'ps_ind_07_bin',
  'ps_ind_08_bin',
  'ps_ind_09_bin',
  'ps_ind_10_bin',
  'ps_ind_11_bin',
  'ps_ind_12_bin',
  'ps_ind_13_bin',
  'ps_ind_16_bin',
  'ps_ind_17_bin',
  'ps_ind_18_bin',
  'ps_car_01_cat',
  'ps_car_02_cat',
  'ps_car_03_cat',
  'ps_car_04_cat',
  'ps_car_05_cat',
  'ps_car_06_cat',
  'ps_car_07_cat',
  'ps_car_08_cat',
  'ps_car_09_cat',
  'ps_car_10_cat',
  'ps_car_11_cat',
  'ps_calc_15_bin',
  'ps_calc_16_bin',
  'ps_calc_17_bin',
  'ps_calc_18_bin',
  'ps_calc_19_bin',
  'ps_calc_20_bin'])

In [9]:
n = len(df)
idxs = get_cv_idxs(n)
val_df = df.iloc[idxs].set_index("id")
# samp_size = len(val_df); samp_size

In [19]:
get_cv_idxs??

In [8]:
val_df.to_csv(f'{PATH}val/valid.csv')

In [37]:
apply_cats??

In [10]:
dep = 'target'
df = df[categorical+continuous+[dep]].copy()

In [11]:
val_df = val_df[categorical+continuous+[dep]].copy()

In [12]:
test[dep] = 0
test = test[categorical+continuous+[dep, 'id']].copy()

In [13]:
for v in categorical: df[v] = df[v].astype('category').cat.as_ordered()

In [14]:
apply_cats(test, df)

In [17]:
apply_cats(val_df, df)

In [15]:
for v in continuous:
    df[v] = df[v].astype('float32')
    test[v] = test[v].astype('float32')

In [16]:
len(df)

595212

In [14]:
df.to_feather(f'{PATH}train_df')
test.to_feather(f'{PATH}test_df')

In [14]:
df = pd.read_feather(f'{PATH}train_df')
test = pd.read_feather(f'{PATH}test_df')

In [15]:
df.head(2)

,ps_ind_02_cat,ps_ind_04_cat,ps_ind_05_cat,ps_ind_06_bin,ps_ind_07_bin,ps_ind_08_bin,ps_ind_09_bin,ps_ind_10_bin,ps_ind_11_bin,ps_ind_12_bin,...,ps_calc_06,ps_calc_07,ps_calc_08,ps_calc_09,ps_calc_10,ps_calc_11,ps_calc_12,ps_calc_13,ps_calc_14,target
0,2,1,0,0,1,0,0,0,0,0,...,10.0,1.0,10.0,1.0,5.0,9.0,1.0,5.0,8.0,0
1,1,0,0,0,0,1,0,0,0,0,...,9.0,5.0,8.0,1.0,7.0,3.0,1.0,1.0,9.0,0

In [17]:
df, y, nas, mapper = proc_df(df, 'target', do_scale=True)
yl = np.log(y)

/home/bmn/anaconda3/envs/fastai/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log

In [18]:
test = test.set_index("id")

In [20]:
df_test, _, nas, mapper = proc_df(test, 'target', do_scale=True,
                                  mapper=mapper, na_dict=nas)

In [21]:
train_ratio = 0.75
# train_ratio = 0.9
train_size = int(len(df) * train_ratio); train_size
val_idx = list(range(train_size, len(df)))

In [22]:
val_idx

[446409,
 446410,
 446411,
 446412,
 446413,
 446414,
 446415,
 446416,
 446417,
 446418,
 446419,
 446420,
 446421,
 446422,
 446423,
 446424,
 446425,
 446426,
 446427,
 446428,
 446429,
 446430,
 446431,
 446432,
 446433,
 446434,
 446435,
 446436,
 446437,
 446438,
 446439,
 446440,
 446441,
 446442,
 446443,
 446444,
 446445,
 446446,
 446447,
 446448,
 446449,
 446450,
 446451,
 446452,
 446453,
 446454,
 446455,
 446456,
 446457,
 446458,
 446459,
 446460,
 446461,
 446462,
 446463,
 446464,
 446465,
 446466,
 446467,
 446468,
 446469,
 446470,
 446471,
 446472,
 446473,
 446474,
 446475,
 446476,
 446477,
 446478,
 446479,
 446480,
 446481,
 446482,
 446483,
 446484,
 446485,
 446486,
 446487,
 446488,
 446489,
 446490,
 446491,
 446492,
 446493,
 446494,
 446495,
 446496,
 446497,
 446498,
 446499,
 446500,
 446501,
 446502,
 446503,
 446504,
 446505,
 446506,
 446507,
 446508,
 446509,
 446510,
 446511,
 446512,
 446513,
 446514,
 446515,
 446516,
 446517,
 446518,
 446519,
 446520,
 446521,
 446522,
 446523,
 446524,
 446525,
 446526,
 446527,
 446528,
 446529,
 446530,
 446531,
 446532,
 446533,
 446534,
 446535,
 446536,
 446537,
 446538,
 446539,
 446540,
 446541,
 446542,
 446543,
 446544,
 446545,
 446546,
 446547,
 446548,
 446549,
 446550,
 446551,
 446552,
 446553,
 446554,
 446555,
 446556,
 446557,
 446558,
 446559,
 446560,
 446561,
 446562,
 446563,
 446564,
 446565,
 446566,
 446567,
 446568,
 446569,
 446570,
 446571,
 446572,
 446573,
 446574,
 446575,
 446576,
 446577,
 446578,
 446579,
 446580,
 446581,
 446582,
 446583,
 446584,
 446585,
 446586,
 446587,
 446588,
 446589,
 446590,
 446591,
 446592,
 446593,
 446594,
 446595,
 446596,
 446597,
 446598,
 446599,
 446600,
 446601,
 446602,
 446603,
 446604,
 446605,
 446606,
 446607,
 446608,
 446609,
 446610,
 446611,
 446612,
 446613,
 446614,
 446615,
 446616,
 446617,
 446618,
 446619,
 446620,
 446621,
 446622,
 446623,
 446624,
 446625,
 446626,
 446627,
 446628,
 446629,
 446630,
 446631,
 446632,
 446633,
 446634,
 446635,
 446636,
 446637,
 446638,
 446639,
 446640,
 446641,
 446642,
 446643,
 446644,
 446645,
 446646,
 446647,
 446648,
 446649,
 446650,
 446651,
 446652,
 446653,
 446654,
 446655,
 446656,
 446657,
 446658,
 446659,
 446660,
 446661,
 446662,
 446663,
 446664,
 446665,
 446666,
 446667,
 446668,
 446669,
 446670,
 446671,
 446672,
 446673,
 446674,
 446675,
 446676,
 446677,
 446678,
 446679,
 446680,
 446681,
 446682,
 446683,
 446684,
 446685,
 446686,
 446687,
 446688,
 446689,
 446690,
 446691,
 446692,
 446693,
 446694,
 446695,
 446696,
 446697,
 446698,
 446699,
 446700,
 446701,
 446702,
 446703,
 446704,
 446705,
 446706,
 446707,
 446708,
 446709,
 446710,
 446711,
 446712,
 446713,
 446714,
 446715,
 446716,
 446717,
 446718,
 446719,
 446720,
 446721,
 446722,
 446723,
 446724,
 446725,
 446726,
 446727,
 446728,
 446729,
 446730,
 446731,
 446732,
 446733,
 446734,
 446735,
 446736,
 446737,
 446738,
 446739,
 446740,
 446741,
 446742,
 446743,
 446744,
 446745,
 446746,
 446747,
 446748,
 446749,
 446750,
 446751,
 446752,
 446753,
 446754,
 446755,
 446756,
 446757,
 446758,
 446759,
 446760,
 446761,
 446762,
 446763,
 446764,
 446765,
 446766,
 446767,
 446768,
 446769,
 446770,
 446771,
 446772,
 446773,
 446774,
 446775,
 446776,
 446777,
 446778,
 446779,
 446780,
 446781,
 446782,
 446783,
 446784,
 446785,
 446786,
 446787,
 446788,
 446789,
 446790,
 446791,
 446792,
 446793,
 446794,
 446795,
 446796,
 446797,
 446798,
 446799,
 446800,
 446801,
 446802,
 446803,
 446804,
 446805,
 446806,
 446807,
 446808,
 446809,
 446810,
 446811,
 446812,
 446813,
 446814,
 446815,
 446816,
 446817,
 446818,
 446819,
 446820,
 446821,
 446822,
 446823,
 446824,
 446825,
 446826,
 446827,
 446828,
 446829,
 446830,
 446831,
 446832,
 446833,
 446834,
 446835,
 446836,
 446837,
 446838,
 446839,
 446840,
 446841,
 446842,
 446843,
 446844,
 446845,
 446846,
 446847,
 446848,
 446849,
 446850,
 446851,
 446852,
 446853,
 446854,
 446855,
 446856,
 446857,
 446858,
 446859,
 446860,
 446861,
 446862,
 446863,
 446864,
 446865,
 446866,
 446867,
 446868,
 446869,
 446870,
 446871,
 446872,
 446873,
 446874,
 446875,
 446876,
 446877,
 446878,
 446879,
 446880,
 446881,
 446882,
 446883,
 446884,
 446885,
 446886,
 446887,
 446888,
 446889,
 446890,
 446891,
 446892,
 446893,
 446894,
 446895,
 446896,
 446897,
 446898,
 446899,
 446900,
 446901,
 446902,
 446903,
 446904,
 446905,
 446906,
 446907,
 446908,
 446909,
 446910,
 446911,
 446912,
 446913,
 446914,
 446915,
 446916,
 446917,
 446918,
 446919,
 446920,
 446921,
 446922,
 446923,
 446924,
 446925,
 446926,
 446927,
 446928,
 446929,
 446930,
 446931,
 446932,
 446933,
 446934,
 446935,
 446936,
 446937,
 446938,
 446939,
 446940,
 446941,
 446942,
 446943,
 446944,
 446945,
 446946,
 446947,
 446948,
 446949,
 446950,
 446951,
 446952,
 446953,
 446954,
 446955,
 446956,
 446957,
 446958,
 446959,
 446960,
 446961,
 446962,
 446963,
 446964,
 446965,
 446966,
 446967,
 446968,
 446969,
 446970,
 446971,
 446972,
 446973,
 446974,
 446975,
 446976,
 446977,
 446978,
 446979,
 446980,
 446981,
 446982,
 446983,
 446984,
 446985,
 446986,
 446987,
 446988,
 446989,
 446990,
 446991,
 446992,
 446993,
 446994,
 446995,
 446996,
 446997,
 446998,
 446999,
 447000,
 447001,
 447002,
 447003,
 447004,
 447005,
 447006,
 447007,
 447008,
 447009,
 447010,
 447011,
 447012,
 447013,
 447014,
 447015,
 447016,
 447017,
 447018,
 447019,
 447020,
 447021,
 447022,
 447023,
 447024,
 447025,
 447026,
 447027,
 447028,
 447029,
 447030,
 447031,
 447032,
 447033,
 447034,
 447035,
 447036,
 447037,
 447038,
 447039,
 447040,
 447041,
 447042,
 447043,
 447044,
 447045,
 447046,
 447047,
 447048,
 447049,
 447050,
 447051,
 447052,
 447053,
 447054,
 447055,
 447056,
 447057,
 447058,
 447059,
 447060,
 447061,
 447062,
 447063,
 447064,
 447065,
 447066,
 447067,
 447068,
 447069,
 447070,
 447071,
 447072,
 447073,
 447074,
 447075,
 447076,
 447077,
 447078,
 447079,
 447080,
 447081,
 447082,
 447083,
 447084,
 447085,
 447086,
 447087,
 447088,
 447089,
 447090,
 447091,
 447092,
 447093,
 447094,
 447095,
 447096,
 447097,
 447098,
 447099,
 447100,
 447101,
 447102,
 447103,
 447104,
 447105,
 447106,
 447107,
 447108,
 447109,
 447110,
 447111,
 447112,
 447113,
 447114,
 447115,
 447116,
 447117,
 447118,
 447119,
 447120,
 447121,
 447122,
 447123,
 447124,
 447125,
 447126,
 447127,
 447128,
 447129,
 447130,
 447131,
 447132,
 447133,
 447134,
 447135,
 447136,
 447137,
 447138,
 447139,
 447140,
 447141,
 447142,
 447143,
 447144,
 447145,
 447146,
 447147,
 447148,
 447149,
 447150,
 447151,
 447152,
 447153,
 447154,
 447155,
 447156,
 447157,
 447158,
 447159,
 447160,
 447161,
 447162,
 447163,
 447164,
 447165,
 447166,
 447167,
 447168,
 447169,
 447170,
 447171,
 447172,
 447173,
 447174,
 447175,
 447176,
 447177,
 447178,
 447179,
 447180,
 447181,
 447182,
 447183,
 447184,
 447185,
 447186,
 447187,
 447188,
 447189,
 447190,
 447191,
 447192,
 447193,
 447194,
 447195,
 447196,
 447197,
 447198,
 447199,
 447200,
 447201,
 447202,
 447203,
 447204,
 447205,
 447206,
 447207,
 447208,
 447209,
 447210,
 447211,
 447212,
 447213,
 447214,
 447215,
 447216,
 447217,
 447218,
 447219,
 447220,
 447221,
 447222,
 447223,
 447224,
 447225,
 447226,
 447227,
 447228,
 447229,
 447230,
 447231,
 447232,
 447233,
 447234,
 447235,
 447236,
 447237,
 447238,
 447239,
 447240,
 447241,
 447242,
 447243,
 447244,
 447245,
 447246,
 447247,
 447248,
 447249,
 447250,
 447251,
 447252,
 447253,
 447254,
 447255,
 447256,
 447257,
 447258,
 447259,
 447260,
 447261,
 447262,
 447263,
 447264,
 447265,
 447266,
 447267,
 447268,
 447269,
 447270,
 447271,
 447272,
 447273,
 447274,
 447275,
 447276,
 447277,
 447278,
 447279,
 447280,
 447281,
 447282,
 447283,
 447284,
 447285,
 447286,
 447287,
 447288,
 447289,
 447290,
 447291,
 447292,
 447293,
 447294,
 447295,
 447296,
 447297,
 447298,
 447299,
 447300,
 447301,
 447302,
 447303,
 447304,
 447305,
 447306,
 447307,
 447308,
 447309,
 447310,
 447311,
 447312,
 447313,
 447314,
 447315,
 447316,
 447317,
 447318,
 447319,
 447320,
 447321,
 447322,
 447323,
 447324,
 447325,
 447326,
 447327,
 447328,
 447329,
 447330,
 447331,
 447332,
 447333,
 447334,
 447335,
 447336,
 447337,
 447338,
 447339,
 447340,
 447341,
 447342,
 447343,
 447344,
 447345,
 447346,
 447347,
 447348,
 447349,
 447350,
 447351,
 447352,
 447353,
 447354,
 447355,
 447356,
 447357,
 447358,
 447359,
 447360,
 447361,
 447362,
 447363,
 447364,
 447365,
 447366,
 447367,
 447368,
 447369,
 447370,
 447371,
 447372,
 447373,
 447374,
 447375,
 447376,
 447377,
 447378,
 447379,
 447380,
 447381,
 447382,
 447383,
 447384,
 447385,
 447386,
 447387,
 447388,
 447389,
 447390,
 447391,
 447392,
 447393,
 447394,
 447395,
 447396,
 447397,
 447398,
 447399,
 447400,
 447401,
 447402,
 447403,
 447404,
 447405,
 447406,
 447407,
 447408,
 ...]

In [23]:
def inv_y(a): return np.exp(a)

def exp_rmspe(y_pred, targ):
    targ = inv_y(targ)
    pct_var = (targ - inv_y(y_pred))/targ
    return math.sqrt((pct_var**2).mean())

max_log_y = np.max(yl)
y_range = (0, max_log_y*1.2)

In [24]:
y_range

(0, 0.0)

In [25]:
max_log_y

0.0

In [26]:
target

NameError: name 'target' is not defined

In [27]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])